### ISSUE TITLE
Implement an initial tree (part 1 of 4)

### ISSUE THREAD

**Issue by raukas** [imerilo1100/TVP2015#12]
1.1. Generate any arbitrary initial tree (can be hardcoded for first implementation).

**Comment by MadisKarli** [comment]
https://github.com/imerilo1100/TVP2015/commit/27fa23d0c0c8a7e630aaf237f62aefecd0a26ad3

**Comment by MadisKarli** [comment]
[UC1](https://github.com/imerilo1100/TVP2015/wiki/Use-Cases#use-case-1)
