### ISSUE TITLE
Implement an initial tree (part 2 of 4)

### ISSUE THREAD

**Issue by raukas** [imerilo1100/TVP2015#13]
1.2. Generate an arbitrary initial tree with the specified number of nodes and/or edges.

**Comment by raukas** [comment]
[UC1](https://github.com/imerilo1100/TVP2015/wiki/Use-Cases)
[UC2](https://github.com/imerilo1100/TVP2015/wiki/Use-Cases)

**Comment by InSpe** [comment]
27fa23d
