### ISSUE TITLE
Implement the random modification functionality

### ISSUE THREAD

**Issue by raukas** [imerilo1100/TVP2015#14]
2.1 Relocating a random edge. The implementation must be equivalent to picking a random edge not in the graph, adding it to the tree, and then removing any conflicting edges (that would result in loops) without breaking the tree into sub-trees.

**Comment by raukas** [comment]
[UC2](https://github.com/imerilo1100/TVP2015/wiki/Use-Cases)

**Comment by MadisKarli** [comment]
https://github.com/imerilo1100/TVP2015/commit/ae9c32dd39145230f57210df015ca0084dce82ea
