### ISSUE TITLE
Implement graphical user interface

### ISSUE THREAD

**Issue by raukas** [imerilo1100/TVP2015#15]
3.0 The app must have a graphical user interface (GUI) consisting of two parts: a canvas for displaying trees (right), and a statistics area (left).

**Comment by raukas** [comment]
[UC1](https://github.com/imerilo1100/TVP2015/wiki/Use-Cases)
[UC2](https://github.com/imerilo1100/TVP2015/wiki/Use-Cases)

**Comment by MadisKarli** [comment]
https://github.com/imerilo1100/TVP2015/commit/27fa23d0c0c8a7e630aaf237f62aefecd0a26ad3
