### ISSUE TITLE
Non-functional requirements

### ISSUE THREAD

**Issue by raukas** [imerilo1100/TVP2015#2]
Non-functional requirements must be written in the Wiki.

(We have listed the most important non-functional requirements. There is at least seven measurable non-functional requirements present. Need to explain how we are going to measure whether the system satisfies a given requirement.)

**Comment by MadisKarli** [comment]
First seven: https://github.com/imerilo1100/TVP2015/wiki/Non-functional-Requirements

**Comment by raukas** [comment]
Done
