### ISSUE TITLE
Automatic build errors, resolve device-specific (?) compatibility errors. 

### ISSUE THREAD

**Issue by imerilo1100** [imerilo1100/TVP2015#36]
Maven does not appear to recognize the git version of the project as valid on neither of my devices. Annotations, mouse input and beans do not work as intended. Has been issue since Maven compatibility changes.

**Comment by InSpe** [comment]
Travis builds again successfully after 3caf32e. It's important not to run `mvn eclipse:clean`, as it deletes the .settings directory, which is necessary to work with eclipse. Running `mvn eclipse:eclipse` generates the necessary .project and .classpath file for eclipse, the remaining can be found from .settings directory.
